""" Sample TensorFlow XML-to-TFRecord converter

optional arguments:
  -h, --help            show this help message and exit
  -x XML_DIR, --xml_dir XML_DIR
                        Path to the folder where the input .xml files are stored.
  -l LABELS_PATH, --labels_path LABELS_PATH
                        Path to the labels (.pbtxt) file.
  -o OUTPUT_PATH, --output_path OUTPUT_PATH
                        Path of output TFRecord (.record) file.
  -i IMAGE_DIR, --image_dir IMAGE_DIR
                        Path to the folder where the input image files are stored. Defaults to the same directory as XML_DIR.
  -c CSV_PATH, --csv_path CSV_PATH
                        Path of output .csv file. If none provided, then no file will be written.
"""

import os
import glob
import pandas as pd
import io
import xml.etree.ElementTree as ET
import argparse

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # Suppress TensorFlow logging (1)
import tensorflow.compat.v1 as tf
from PIL import Image
from object_detection.utils import dataset_util, label_map_util
from collections import namedtuple


XML_DIR = './../../workspace/v0.0.1/train_test_images/train/'
LABELS_PATH = './../../workspace/v0.0.1/annotations/label_map.pbtxt'
OUTPUT_PATH = './../../workspace/v0.0.1/annotations/train.record'
IMAGE_DIR = None
CSV_PATH = None

LABEL_MAP = label_map_util.load_labelmap(LABELS_PATH)
LABEL_MAP_DICT = label_map_util.get_label_map_dict(LABEL_MAP)


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines
    them in a single Pandas dataframe.

    Parameters:
    ----------
    path : str
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """

    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        root = tree.getroot()
        filename = root.find('filename').text
        width = int(root.find('size').find('width').text)
        height = int(root.find('size').find('height').text)
        for member in root.findall('object'):
            bndbox = member.find('bndbox')
            value = (filename,
                     width,
                     height,
                     member.find('name').text,
                     int(bndbox.find('xmin').text),
                     int(bndbox.find('ymin').text),
                     int(bndbox.find('xmax').text),
                     int(bndbox.find('ymax').text),
                     )
            xml_list.append(value)
    column_name = ['filename', 'width', 'height',
                   'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


def class_text_to_int(row_label):
    return LABEL_MAP_DICT[row_label]


def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]


def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    #encoded_jpg_io = io.BytesIO(encoded_jpg)
    #image = Image.open(encoded_jpg_io)
    #width, height = image.size

    filename = group.filename.encode('utf8')
    image_format = b'jpg'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []

    for index, row in group.object.iterrows():
        width, height = row['width'], row['height']
        xmin = row['xmin'] / width
        xmax = row['xmax'] / width
        ymin = row['ymin'] / height
        ymax = row['ymax'] / height

        # sanity checks to make sure the annotations are correct
        if xmin < 0:
            print(f"[WARNING] Error with {filename.decode()}, xmin {xmin} < 0")
            print(f"xmin = {xmin}; width = {width}")
        if xmax > 1:
            print(f"[WARNING] Error with {filename.decode()}, xmax {xmax} > 1")
            print(f"xmax = {xmax}; height = {height}")
        if ymin < 0:
            print(f"[WARNING] Error with {filename.decode()}, ymin {ymin} < 0")
            print(f"ymin = {ymin}; height = {height}")
        if ymax > 1:
            print(f"[WARNING] Error with {filename.decode()}, ymax {ymax} > 1")
            print(f"ymax = {ymax}; height = {height}")

        xmins.append(xmin)
        xmaxs.append(xmax)
        ymins.append(ymin)
        ymaxs.append(ymax)

        classes_text.append(row['class'].encode('utf8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example


def main(_):

    writer = tf.python_io.TFRecordWriter(OUTPUT_PATH)
    path = os.path.join(IMAGE_DIR)
    examples = xml_to_csv(XML_DIR)
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())
    writer.close()
    print('Successfully created the TFRecord file: {}'.format(OUTPUT_PATH))
    if CSV_PATH is not None:
        examples.to_csv(CSV_PATH, index=None)
        print('Successfully created the CSV file: {}'.format(CSV_PATH))


if __name__ == '__main__':
    if IMAGE_DIR is None:
        IMAGE_DIR = XML_DIR

    tf.app.run()
